# Generated by Django 5.0.6 on 2024-05-14 18:05

import django.utils.timezone
import phonenumber_field.modelfields
import user.manager
import user.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('email', models.EmailField(error_messages={'message': '이미 email이 존재합니다'}, max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, validators=[user.validators.UnicodeUsernameValidator])),
                ('birthday', models.DateField(null=True)),
                ('location', models.CharField(help_text={'message': '사는 곳을 꼭 입력해주세요'}, max_length=100)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(help_text={'message': '휴대전화 번호를 입력해주세요(- 붙여서 적어주세요)'}, max_length=128, region='KR')),
                ('point', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('Role', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Admin'), (1, 'Staff'), (0, 'common_user')], default=0, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
    ]
