# Generated by Django 5.0.6 on 2024-05-16 17:40

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 존재하는 이메일 입니다. 다른 이메일을 작성해주세요'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(help_text={'message': '휴대전화 번호를 정확히 입력해주세요'}, max_length=20, validators=[user.validators.UnicodeNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, validators=[user.validators.UnicodeUsernameValidator()]),
        ),
    ]
