# Generated by Django 5.0.6 on 2024-05-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_uid_user_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
    ]
